when:
  event: cron
  cron: sync-products-jmbottazzi-cron

steps:
  - name: sync-products-jmbottazzi-cron
    image: node:18-alpine
    environment:
      ACCESS_TOKEN_BOTTAZZI:
        from_secret: access_token_bottazzi
    commands:
      - echo "Sync triggered by cron"
      - npm install
      - npm run sync
